// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportClip(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportClip'](arg1, arg2, arg3, arg4);
}

export function FetchDirectory() {
  return window['go']['main']['App']['FetchDirectory']();
}

export function GetLatestVideos(arg1) {
  return window['go']['main']['App']['GetLatestVideos'](arg1);
}

export function GetSaveLocation() {
  return window['go']['main']['App']['GetSaveLocation']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetWatchLocation() {
  return window['go']['main']['App']['GetWatchLocation']();
}

export function SaveSaveLocation(arg1) {
  return window['go']['main']['App']['SaveSaveLocation'](arg1);
}

export function SaveWatchLocation(arg1) {
  return window['go']['main']['App']['SaveWatchLocation'](arg1);
}

export function SelectVideo() {
  return window['go']['main']['App']['SelectVideo']();
}
