// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportClip(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function FetchDirectory():Promise<string>;

export function GetLatestVideos(arg1:string):Promise<Array<main.VideoFile>>;

export function GetSaveLocation():Promise<string>;

export function GetThumbnail(arg1:string):Promise<Array<number>>;

export function GetWatchLocation():Promise<string>;

export function SaveSaveLocation(arg1:string):Promise<void>;

export function SaveWatchLocation(arg1:string):Promise<void>;

export function SelectVideo():Promise<string>;
