// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CropVideo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CropVideo'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportClip(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ExportClip'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function FetchDirectory() {
  return window['go']['main']['App']['FetchDirectory']();
}

export function GetExportSettings() {
  return window['go']['main']['App']['GetExportSettings']();
}

export function GetLatestVideos(arg1) {
  return window['go']['main']['App']['GetLatestVideos'](arg1);
}

export function GetSaveLocation() {
  return window['go']['main']['App']['GetSaveLocation']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function GetWatchLocation() {
  return window['go']['main']['App']['GetWatchLocation']();
}

export function HandleFileUpload(arg1, arg2) {
  return window['go']['main']['App']['HandleFileUpload'](arg1, arg2);
}

export function SaveExportSettings(arg1) {
  return window['go']['main']['App']['SaveExportSettings'](arg1);
}

export function SaveSaveLocation(arg1) {
  return window['go']['main']['App']['SaveSaveLocation'](arg1);
}

export function SaveWatchLocation(arg1) {
  return window['go']['main']['App']['SaveWatchLocation'](arg1);
}

export function SelectVideo() {
  return window['go']['main']['App']['SelectVideo']();
}
