// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchDirectory() {
  return window['go']['main']['App']['FetchDirectory']();
}

export function GetLatestVideos(arg1) {
  return window['go']['main']['App']['GetLatestVideos'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
